DTS-STN/vacman

- frontend/app/.server/locales/app-fr.json
- frontend/tests/components/__snapshots__/input-textarea.test.tsx.snap
fix failing type check and failing test
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or screen-recordings …
> bugfix(frontend): fix failing typecheck and failing test

- frontend/app/routes/index.tsx
- frontend/app/routes/profile/employment-information.tsx
- frontend/app/routes/profile/index.tsx
- frontend/app/routes/profile/personal-details.tsx
- frontend/app/routes/profile/personal-information.tsx
- frontend/app/routes/register/index.tsx
- frontend/app/routes/register/privacy-consent.tsx
As of React Router v7.6.1, `Route.MetaArgs.data` can be undefined. This PR fixes compilation errors caused by that change.
See: <https://reactrouter.com/changelog#v761>
> fix(frontend): handle optional documentTitle in meta function

- frontend/app/components/error-summary.tsx
fix error summary component, as it wasn't displaying the error block at the top of page
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): fix error summary component

- frontend/app/.server/domain/services/city-service-default.ts
- frontend/app/.server/domain/services/city-service-mock.ts
- frontend/app/.server/domain/services/city-service.ts
[AB#6284](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6284)
update mock service and default service for city service to use [oxide](https://www.npmjs.com/package/oxide.ts) package to return Option with find and Result with get
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): update city service

- frontend/app/.server/domain/services/classification-service-default.ts
- frontend/app/.server/domain/services/classification-service-mock.ts
- frontend/app/.server/domain/services/classification-service.ts
[AB#6280](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6280)
update mock service and default service for classification service to use [oxide](https://www.npmjs.com/package/oxide.ts) package to return Option with find and Result with get
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): update classification service

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/province-service-default.ts
- frontend/app/.server/domain/services/province-service-mock.ts
- frontend/app/.server/domain/services/province-service.ts
- frontend/tests/.server/domain/services/province-service-mock.test.ts
[AB#6283](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6283)
Updated mock service and default service for province service to use [oxide](https://www.npmjs.com/package/oxide.ts) package to return Option with find and Result with get
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): update province service

- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/CityController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/ClassificationController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/EducationLevelController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/LanguageController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/LanguageReferralTypeController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/WfaStatusController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/WorkUnitController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/CollectionModel.java
- Replaced `List<T>` with `Iterable<T>` in `CollectionModel` for greater flexibility
- Removed unused imports
- Replaced `StringUtils.isNotBlank(..)` with a static import for cleaner syntax
- Inlined local variables to reduce boilerplate and improve readability
- Converted indentation from spaces to tabs
<details>
```shell
```
</details>
<details>
```shell
pnpm run test …
```
> chore(backend): Cleaning up types and imports

- backend/src/main/resources/application.yaml
This PR adds Spring Boot actuator configs to enable monitoring and management endpoints.
Local testing URL: http://localhost:8080/actuator
`/actuator`:
`/actuator/health`:
> chore(backend): Add actuator configuration

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/employment-tenure-service-default.ts
- frontend/app/.server/domain/services/employment-tenure-service-mock.ts
- frontend/app/.server/domain/services/employment-tenure-service.ts
- frontend/app/.server/resources/employmentTenure.json
- frontend/app/routes/employee/[id]/profile/index.tsx
- frontend/app/routes/employee/[id]/profile/referral-preferences.tsx
- frontend/app/routes/employee/[id]/profile/validation.server.ts
[AB#6424](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6424)
[AB#6288](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6288)
update employment tenure service.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): update employment tenure service

- frontend/app/routes/employee/[id]/profile/validation.server.ts
Add validation to WFA date fields, the WFA effective date should be before the end date
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative approaches you …
> refactor(frontend): Add validation to WFA date fields

- backend/pom.xml
> chore(backend): update dependencies

- frontend/app/routes/employee/[id]/profile/index.tsx
[AB#6465](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6465)
Redirect to employee dashboard from view profile.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> redirect to employee dashboard from view profile

- frontend/app/routes/employee/index.tsx
- frontend/app/routes/index.tsx
Stretch the height of the svg image to span the page. 
Note: This is causing vertical scroll
> refactor(frontend): update the height of the svg image to span the page

- backend/src/main/resources/application.yaml
Added connection-timeout, and adjusted the max-lifetime in hikari to hopefully address connection timeout errors
> Adjusting Hikari Settings Due to Connection Warnings in INT

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/employee/[id]/profile/index.tsx
[AB#6479](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6479)
Remove x out of x complete status from employee card as it is removed in design in figma 
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): remove x out of x complete status from employee card

- frontend/app/routes/employee/[id]/profile/index.tsx
> chore(frontend) remove unnecessary console log

- gitops/nonprod/base/vacman-backend/kustomization.yaml
- gitops/nonprod/base/vacman-backend/services.yaml
> chore(gitops): Configure base backend service

- frontend/app/routes/employee/[id]/profile/index.tsx
Fix the responsiveness of `ProfileCard`
Before:
After:
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or …
> fix(frontend) update ProfileCard to be responsive

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/employee/[id]/profile/personal-information.tsx
- frontend/app/routes/employee/[id]/profile/validation.server.ts
[AB#6481](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6481)
Fix the preferred language not showing bug.
Fixed over writing of surname and given name when personal information is saved. **Bug**: When the Personal information was saved, the user name at the top of view profile displays undefined, undefined.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> bugfix(frontend): fix the bugs on employee personal information

- frontend/app/routes/employee/[id]/profile/index.tsx
[AB#6484 update the progress bar](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6484)
Update the progress bar based on Number of required fields completed divided by total number of required fields.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): update the progress bar

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/routes/employee/[id]/profile/index.tsx
- frontend/app/utils/date-utils.ts
[AB#6485](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6485)
Updated the mock service to to record the userUpdated and dateUpdated values
Updated the "updated by" value so that it shows the name of the updater, not the ID
Formatted the date updated in YYYY-MM-DD HH:MM format
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): last modified by changes

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/i18n-routes.ts
- frontend/app/routes/hiring-manager/[id]/profile/employment-information.tsx
- frontend/app/routes/hiring-manager/[id]/profile/index.tsx
- frontend/app/routes/hiring-manager/[id]/profile/personal-information.tsx
- frontend/app/routes/hiring-manager/[id]/profile/referral-preferences.tsx
- frontend/app/routes/hiring-manager/[id]/profile/validation.server.ts
Copied all /profile pages to the hiring manager route.
Updated HM profile index subtitle and removed progress bar.
[AB#6489](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6489)
> Copied /[id]/profile pages to the hiring manager route

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/UserEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/UserCreateModel.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/UserReadModel.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/UserUpdateModel.java
- backend/src/test/java/ca/gov/dtsstn/vacman/api/data/repository/UserRepositoryTest.java
Change all the MsEntraID examples to match, remove straggler UUID references.
> Standardising MSEntraId Examples, Cleaning Up UUID

- backend/src/main/java/ca/gov/dtsstn/vacman/api/event/UserDeletedEvent.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/event/UserReadEvent.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/event/UserUpdatedEvent.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/event/listener/UserEventListener.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/UserService.java
Added events for create, update and delete events for user. Events are not emitted for "get all users" since we won't have that in the API
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include …
> Added crud events for user

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/EventEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/event/listener/UserEventListener.java
This keeps reference to "details" but links it to DETAIL column in the events table. Should fix the pipeline crash
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
> Add details field and reference the DETAIL column

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/routes/employee/profile/index.tsx
After testing and looking through the code base, these todos are resolved and can be removed.
> chore(frontend) remove unnecessary todos

- backend/src/main/java/ca/gov/dtsstn/vacman/api/security/SecurityUtils.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/UsersController.java
Integrate SecurityUtils in users controller.
[AB#6533](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6533) [AB#6534](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6534)
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces …
> refactor(backend): SecurityUtils integration

- frontend/app/.server/utils/privacy-consent-utils.ts
- frontend/app/.server/utils/route-matching-utils.ts
- frontend/app/i18n-routes.ts
- frontend/app/routes/employee/index.tsx
- frontend/app/routes/employee/profile/privacy-consent.tsx
- frontend/app/routes/layout.tsx
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
- frontend/tests/.server/utils/route-matching-utils.test.ts
[AB#6554](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6554)
moves `/privacy-consent` under `/employee/profile`
> refactor(frontend) move /privacy-consent

- frontend/app/.server/domain/services/user-service-default.ts
[AB#6575](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6575)
#341 was correct at the time, but the ticket has been revised with a new url query string.
> fix(frontend) update getUsersByRole default impl

- frontend/app/routes/employee/profile/privacy-consent.tsx
[AB#6561](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6561)
Update privacy consent page action:
If user accepts, call profile service, update privacyConsentInd to true using updateProfile service method.
If user declines, redirect to /employee index (implemented in #338 )
<details>
```shell
```
</details>
<details>
```shell
pnpm run …
```
> refactor(frontend): Update privacy consent page

- frontend/app/routes/employee/profile/employment-information.tsx
per title
[AB#6574](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6574)
> refactor(frontend) use getCurrentProfile in /employment-information

- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/profile-service.ts
- frontend/tests/.server/routes/index.test.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
- frontend/tests/.server/utils/profile-access-utils.test.ts
- frontend/tests/.server/utils/profile-utils.test.ts
[AB#6599](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6599)
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative approaches …
> refactor(frontend): Refactor profile service getProfileById to use apiClient

- frontend/app/.server/domain/services/profile-service-default.ts
[AB#6621](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6621)
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative approaches …
> refactor(frontedn): Update getCurrentUserProfile to use api client

- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
Since I'm preparing to remove `getProfile(activeDirectoryId)` in the profile-service, some of the loaders/actions need to be updated to use the proper/newly available methods in the profile-service.
[AB#6611](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6611)
[AB#6613](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6613)
[AB#6617](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6617)
[AB#6619](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6619)
Before submitting this PR, ensure that you have completed the following. You can fill these …
> refactor(frontend) update loaders/actions in /hr-advisor

- backend/src/main/java/ca/gov/dtsstn/vacman/api/constants/AppConstants.java
`USER_TYPE_CODE` value is `employee`, updated accordingly.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(backend): Fix employee user type value

- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/profile-service.ts
- frontend/app/routes/hr-advisor/employees.tsx
- frontend/tests/.server/domain/services/profile-service-default.test.ts
- frontend/tests/.server/routes/index.test.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
- frontend/tests/.server/utils/profile-access-utils.test.ts
[AB#6598](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6598/)
update getAllProfile() 
The mock data displays on hr-advisor/employees page:
Disclaimer: I need to test it by connecting it to the API yet
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> feat(frontend): update getAllProfiles

- frontend/app/routes/employee/profile/privacy-consent.tsx
remove id params form privacy consent
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): remove id params form privacy consent

- frontend/app/routes/hr-advisor/employees.tsx
Updates the employees table to navigate to the profile of the selected employee by the profileId.
> chore(frontend) update /hr-advisor/employees table to nvaigate to the employee profile

- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
Incremental PR to pull the profile into the page actions in the `hr-advisor/employee-profile` routes.  Also renamed some variables to reflect their underlying type (result vs option).
> refactor(frontend) hr-advisor profile routes

- backend/src/main/java/ca/gov/dtsstn/vacman/api/constants/AppConstants.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/security/SecurityManager.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/ProfileService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/ProfilesController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/ProfileStatusUpdateModel.java
Implement `PUT /api/v1/profiles/{id}/status` endpoint
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> feature(backend): Add PUT /profiles/{id}/status operation

- frontend/app/domain/constants.ts
- frontend/app/routes/employee/index.tsx
> refactor(frontend) use getLanguageOfCorrespondenceService when registering user

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
[AB#6614](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6614)
> refactor(frontend) update action in hr-advisor/employee-profile/personal-information

- frontend/app/routes/hr-advisor/index.tsx
> fix(frontend) page title hr-advisor/index

- backend/src/main/resources/db/changelog/changes/data/db.data.v1.sql
Edited data for CD_EMPLOYMENT_OPPORTUNITY
> EMPLOYMENT_OPPORTUNITY data rework

- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/WorkUnitReadModel.java
Add the nullable field `parent` to the `WorkUnitReadModel`.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(backend): Add parent field to WorkUnitReadModel

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/user-service-mock.ts
- frontend/tests/.server/domain/services/user-service-default.test.ts
- frontend/tests/.server/domain/services/user-service-integration.test.ts
- frontend/tests/.server/domain/services/user-service-mock.test.ts
This pull request significantly expands and modernizes the integration and unit tests for the user service, focusing on both the mock and default implementations. The changes improve test coverage for user lifecycle operations, error handling, pagination, user type filtering, and ensure consistent interfaces and data structures between service variants.
**Major improvements include:**
* Added comprehensive integration tests covering the complete user lifecycle (registration, retrieval, update) for the mock user service, including new tests for filtering by user type and pagination. Error handling scenarios (e.g., non-existent users) are now explicitly tested.
* Introduced integration tests for the default user service using a mocked API client, covering successful API workflows and error …
> refactor(services): update User service mocks and tests

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/user-service-mock.ts
This pull request adds detailed debug logging to the mock implementations of the `ProfileService` and `UserService` in the backend. The new logging provides better visibility into the flow of mock service operations, including method calls, filtering steps, simulated failures, and data mutations. This will help developers trace and debug test scenarios more effectively.
**Debug Logging Enhancements:**
* Added a `debugLog` utility function to both `profile-service-mock.ts` and `user-service-mock.ts` to standardize debug output for each service. [[1]](diffhunk://#diff-35798cb8db5aba72a6e498702d258c7f1b85e877d6f9d85eaa8ba6547c34c118R17-R21) [[2]](diffhunk://#diff-d256ef52f2d88d79c62b837de41c2e4fe3054f338c40718b5f9f08b3e3cc2112R9-R13)
**Profile Service Mock Improvements:**
* Inserted debug …
> refactor(services): enhance debug logging in Profile and User service mocks

- frontend/app/.server/utils/privacy-consent-utils.ts
- frontend/app/.server/utils/profile-utils.ts
- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/privacy-consent.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employees.tsx
- frontend/app/routes/page-components/employees/validation.server.ts
update profile service names in consumers
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or screen-recordings …
> (frontend)update profile service names in consumers

- frontend/tests/.server/utils/privacy-consent-utils.test.ts
This pull request updates and refactors the privacy consent flow unit tests to align with recent changes in the profile and user service APIs. The main focus is on updating mocks and test logic to use new methods and data structures, especially for retrieving user profiles.
**Test refactoring for updated service APIs:**
* Replaces usage of `getCurrentUserProfile` with `getCurrentUserProfiles` in the `mockProfileService` mock, updating all relevant test cases to expect and handle an array of profiles wrapped in an `Ok` result. [[1]](diffhunk://#diff-8b30a6cfafd744c05f14162499a1c09e0b412297f5ac72bccf82a764b72f6874L96-R99) [[2]](diffhunk://#diff-8b30a6cfafd744c05f14162499a1c09e0b412297f5ac72bccf82a764b72f6874L141-R144) [[3]](diffhunk://#diff-8b30a6cfafd744c05f14162499a1c09e0b412297f5ac72bccf8 …
> fix(privacy-consent): update privacy-consent tests to use new methods and models

- frontend/app/routes/hr-advisor/employees.tsx
re-added code to filter profiles to display only completed and approved 
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers understand the …
>  re added filtered profiles

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/profile-service.ts
- frontend/app/.server/utils/profile-utils.ts
- frontend/app/routes/employee/profile/index.tsx
- frontend/tests/.server/domain/services/profile-service-default.test.ts
- frontend/tests/.server/domain/services/profile-service-mock.test.ts
- frontend/tests/.server/routes/index.test.ts
This pull request introduces improvements to the profile completion and submission logic, focusing on stricter type safety, more precise completion checks for referral preferences, and a new service method to fetch the current user's active profile. It also cleans up utility code and updates the profile action logic to use the new structures.
**Profile Service Enhancements**
- Added a new `findCurrentUserProfile` method to the `ProfileService` interface and its default and mock implementations, allowing retrieval of a single active profile for the current user and handling errors when no profile is found. [[1]](diffhunk://#diff-8214cacd4e8f4fa2ed434421e15da15239fe1f7026185bb3bccee7ed221d43efR24-R25) [[2]](diffhunk://#diff-ea09278ac6f5784b74517dddd26c9057c808849c0b0ebebc2aa4de2eddc066b1R69- …
> refactor(employee-profile): update employee profile summary page data handling

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/user-service-mock.ts
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/page-components/employees/personal-information/form.tsx
- frontend/app/routes/page-components/employees/validation.server.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
This pr fixes the breaking changes introduced on the personal information pages. update all fields (except languageOfCorrespondence because Adam is working on it) on the personal information page to align with the model.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain …
> Refactor personal information page

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/routes/hr-advisor/employees.tsx
> refactor(frontend) integration fix for /hr-advisor/employees

- frontend/app/.server/domain/models.ts
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
- frontend/app/routes/page-components/employees/referral-preferences/form.tsx
- frontend/app/routes/page-components/employees/validation.server.ts
Fixes the breaking changes introduced on the referal preference pages. update all fields on the referral preference pages to align with the model. Will work on another pr to update the service call to update the profile data
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, …
> Refactor referral preference pages

- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
Similar to #519 
[AB#6771](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6771)
[AB#6772](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6772)
[AB#6782](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6782)
> refactor(frontend) /employment-information updateProfileById payload

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/utils/privacy-consent-utils.ts
[AB#6797](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6787/) fix mocks to update profile status
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative …
> refactor(frontend): fix mocks to update profile status

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hr-advisor/employees.tsx
An automated scan revealed more contrast issues and an input without an accessible name (for assistive technology to pick up)
> fix(frontend) a11y fixes on hr-advisors/employees

- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
favour convention of referencing `HttpStatusCodes` over hardcoding
> refactor(frontend) remove hardcoded 404

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/AbstractBaseEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/ProfileEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/UserEntity.java
Our event data is too large (exceeding 4000 char limit) in some instances. Ignoring most associations and some fields to make them much smaller
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include …
> Reduce event size with @JsonIgnore

- frontend/app/components/alert-message.tsx
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
Dollars to donuts says the ITAO flags these alerts because of SR/AT inaccessibility.  I'm preemptively adding SR/AT aria to hopefully prevent that.
> refactor(frontend) make alert AT accessible

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
[AB#6804](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6804)
Content changes.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): content change

- frontend/app/.server/domain/services/wfa-status-service-default.ts
- frontend/app/.server/domain/services/wfa-status-service-mock.ts
- frontend/app/.server/resources/currentWFAStatus.json
- frontend/app/domain/constants.ts
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/page-components/employees/employment-information/form.tsx
- frontend/app/routes/page-components/employees/validation.server.ts
[AB#6809](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6809)
WFA Effective date is mandatory, and WFA end date is optional, but shown for certain WFA status options.
Provide screenshots or screen-recordings to help reviewers understand the visual impact of your changes, if relevant.
> refactor(frontend): wfa dates

- frontend/app/components/choice-tags.tsx
[AB#6829](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6829/)
Heading level should only increase by one
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): heading level should only increase by one

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
[AB#6822](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6822/)
Provide descriptive labels
merging to the release branch
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): descriptive labels

- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/hr-advisor/employees.tsx
> fix(frontend) importing of serverEnvironment

- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hiring-manager/request/position-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
- frontend/tests/components/date-picker-field.test.tsx
- frontend/tests/components/dropdown-menu.test.tsx
> refactor(frontend) string don't need to be square-bracketed in react

- frontend/app/.server/resources/requestStatus.json
- frontend/app/domain/constants.ts
> chore(frontend) update requestStatus.json

- frontend/app/i18n-routes.ts
According to ADO, this route needs to be updated.
> refactor(frontend) update profile view route

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/Ownable.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/ProfileEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/RequestEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/UserEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/security/OwnershipPermissionEvaluator.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/RequestService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/RequestsController.java
Adding some of the logic to the requests endpoints based on requirements outlined in ADO and Miro wireframes. 
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
> Requests API endpoints - part 1

- frontend/app/i18n-routes.ts
- frontend/app/routes/hr-advisor/request/index.tsx
- frontend/app/routes/hr-advisor/request/match.tsx
- frontend/app/routes/hr-advisor/request/matches.tsx
- frontend/app/routes/hr-advisor/request/position-information.tsx
- frontend/app/routes/hr-advisor/request/process-information.tsx
- frontend/app/routes/hr-advisor/request/profile.tsx
- frontend/app/routes/hr-advisor/request/somc-conditions.tsx
- frontend/app/routes/hr-advisor/request/submission-details.tsx
- frontend/app/routes/hr-advisor/requests.tsx
[AB#6868](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6868)
Similar to #448, but for hr-advisor requests now
> feat(frontend) scaffold hr-adivsor request pages

- frontend/app/routes/hr-advisor/request/somc-conditions.tsx
- frontend/app/routes/page-components/requests/somc-conditions/form.tsx
Add somc condition on hr advisor route
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> feat(frontend): add somc condition on hr advisor route

- .github/CODEOWNERS
> feat(project): add `CODEOWNERS` file that protects gitops/prod

- frontend/.env.example
> fix(frontend) eggregious spelling mistakes

- frontend/app/routes/hiring-manager/request/process-information.tsx
- frontend/app/routes/page-components/requests/validation.server.ts
Created process-information page action and validation logic
[AB#6719](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6719)
> Created process-information page action and validation

- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
fix hr advisor route for business email address.
on the hr advisor route, hr advisor is reviewing someone else's profile, this form should never use current user information (that's something that was copy pasted from the employee route)
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers understand the visual impact of your changes, if relevant.
> bug fix(frontend): fix hr advisor route for business email address

- frontend/app/.server/locales/app-fr.ts
- frontend/app/components/input-multiselect.tsx
- frontend/app/routes/employee/profile/privacy-consent.tsx
- frontend/app/routes/layout.tsx
The ITAO is using `dev` as the environment for doing audits.  They have given us outstanding issues (roughly 3-4) related to code that isn't in our upcoming release.  Instead of pushing back on this, it's probably easiest to just apply the 'simple' fixes they want and call it day.
> cherry pick #763 #762 #759 #758 into main

- frontend/app/routes/employee/profile/index.tsx
This pull request makes minor changes to the `frontend/app/routes/employee/profile/index.tsx` file by explicitly specifying boolean types for certain state variables and loader values. This change fixes a linting issue that came up after some type updates.
> fix(profile): add type annotations for employment and referral  preference change flags

- frontend/tests/.server/domain/services/request-service-default.test.ts
- frontend/tests/.server/domain/services/request-service-mock.test.ts
Added starter unit tests for the request service.
Tests cover basic request retrieval, creation, update, and error handling.
This is an initial test suite, more test cases and scenarios could be added in future PRs to improve coverage
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant …
> refactor(frontend): Unit test for request service

- frontend/app/.server/domain/services/request-service-default.ts
- frontend/app/.server/domain/services/request-service-mock.ts
- frontend/app/.server/domain/services/request-service.ts
- frontend/app/domain/constants.ts
- frontend/app/routes/hiring-manager/request/index.tsx
Updated the updateRequestStatus method to align with the backend service.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide …
> refactor(frontend): updateRequestStatus service method

- frontend/containerfile
> chore(frontend): bump node version in `containerfile`

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/components/alert-message.tsx
- frontend/app/components/status-tag.tsx
- frontend/app/components/vacman-background.tsx
- frontend/app/domain/constants.ts
- frontend/app/routes/hr-advisor/request/matches.tsx
- frontend/app/routes/page-components/requests/tables/matches-tables.tsx
- frontend/tests/components/__snapshots__/vacman-background.test.tsx.snap
- frontend/tests/components/vacman-background.test.tsx
[AB#6898](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6898/)
- Updated the `alert-message.tsx` component to support `ReactNode` as it would mess up formatting certain components like `<Trans>`
- Updated `constants.ts` to have request status codes
- Updated the `status-tag.tsx` component to support request status codes
- Added a `vacman-background.tsx` component for reusability 
- Added tests for `vacman-background.tsx`
- Added `matches-list.tsx`
- Updated locales
<details> …
> feat(frontend): add request matches page

- backend/src/main/java/ca/gov/dtsstn/vacman/api/config/properties/GcNotifyProperties.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/NotificationService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/RequestService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/RequestStatusUpdateModel.java
- backend/src/main/resources/application.yaml
```
If the event is submitFeedback
Requestor is Owner of the request
Current Status is FDBK_PENDING
If it is,
then the status is set to FDBK_PEND_APPR
Loop through all the matches under the requestId and set match status to PENDING
send a notification with the Feedback Completed template, sent to the HR Advisor
If not, should return a 404
```
<details>
```shell
```
</details>
<details>
<summary>Unit and e2e …
> Requests - submit feedback event

- frontend/app/routes/hiring-manager/request/process-information.tsx
- frontend/app/routes/hr-advisor/request/process-information.tsx
- frontend/app/routes/page-components/requests/validation.server.ts
Resolves a todo I created for creating a `parseProcessInformation` validation function similar to what's being done in /employment-information
> refactor(frontend) parseProcessInformation

- frontend/app/.server/domain/services/mock-data.ts
- frontend/app/.server/domain/services/request-service-mock.ts
- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/components/status-tag.tsx
- frontend/app/routes/hiring-manager/request/index.tsx
Update page action to handle request submission and update status. Resolved some Todos and clean up comments. 
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
> refactor(frontend): Hiring manager request page - submit request

- frontend/app/components/status-tag.tsx
- frontend/app/domain/constants.ts
akes the code more readable IMO
> refactor(frontend) StatusTag component

- backend/src/main/java/ca/gov/dtsstn/vacman/api/config/LiquibaseConfig.java
- backend/src/main/resources/application-local.yaml.example
- backend/src/main/resources/application.yaml
- backend/src/test/resources/application-test.yaml
- gitops/nonprod/overlays/dev/configs/vacman-backend.yaml
- gitops/nonprod/overlays/int/configs/vacman-backend.yaml
- gitops/nonprod/overlays/uat/configs/vacman-backend.yaml
- gitops/prod/configs/vacman-backend.yaml
This alters the default behaviour of liquibase to throw an exception if no contexts are set. It also changes the application.yaml(s) and gitops configs to set the contexts
- [x ] 💥 **breaking change** -- change that causes existing functionality to no longer work as expected
> Adding liquibaseconfig to catch empty contexts, and changing defaults accordingly

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hr-advisor/request/matches.tsx
- frontend/app/routes/page-components/requests/tables/matches-tables.tsx
[AB#6898](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6898/)
Added popups for comment and approve in `matches-tables.tsx`
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, …
> feat(frontend): add comment and approve popups for matches

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/page-components/employees/referral-preferences/form.tsx
[AB#6975](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6975)
Updated contents on referral preferences route
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
The contents of the collapsible are announced by the screen reader for  Classifications multi …
> refactor(frontend): update contents

- frontend/app/components/status-tag.tsx
Added request status options to the statusTag component
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or …
> fix(frontend): request status tag not showing on request page

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hiring-manager/request/index.tsx
[AB#6716](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6716)
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative approaches …
> refactor(frontend) hiring manager request page - delete request by id

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hiring-manager/request/submission-details.tsx
- frontend/app/routes/hr-advisor/request/submission-details.tsx
[AB#6894](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6894/)
display the form error in case user is not created or found
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers understand the visual …
> refactor(frontend): display form error in case user is not created or found

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/locales/gcweb-en.ts
- frontend/app/.server/locales/gcweb-fr.ts
- frontend/app/components/data-table.tsx
- frontend/app/routes/hr-advisor/employees.tsx
This pull request introduces server-side sorting for the HR Advisor Employee Dashboard table, allowing users to sort employee data by name, email, or last updated date. The sorting state is synchronized with the URL, ensuring consistent behavior across navigation and filtering. The implementation includes strong typing and mapping between frontend column IDs and backend sort properties, as well as accessibility improvements for screen reader announcements.
**Server-side sorting integration:**
* Added a `sort` field to the `ProfileQueryParams` type and ensured the backend receives the correct sorting parameter when fetching profiles (`models.ts`, `profile-service-default.ts`). [[1]](diffhunk://#diff-4125e7b7867b4c3b61c56b95639d0052e515ac7a8897b59171f5598a8bc0d0d0R237) …
> feat(frontend): allow controlled sorting in hr-advisors/employees DataTable

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/i18n-routes.ts
- frontend/app/routes/hiring-manager/request/matches.tsx
- frontend/app/routes/hr-advisor/request/matches.tsx
- frontend/app/routes/page-components/requests/tables/matches-tables.tsx
[AB#6749](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6749/)
Added `hiring-manager/request/matches.tsx`
- Updated `matches-table.tsx`
- Updated locales
- Updated route `hiring-manager/request/profile` to use `profileId` instead of `matchId`
- Updated the document title for both `.../request/matches.tsx` pages
<details>
```shell
```
</details>
<details>
```shell …
```
> feat(frontend): add matches for hiring manager

- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
Per title.. It might be remnant of grand refractor, when the models in front end were changed. The profile have all the information, so we don't need to call services to retrieve the names.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any …
> refactor(frontend): remove duplicate code for converting ids to display name

- frontend/app/routes/hr-advisor/employees.tsx
This pull request includes minor improvements to the `EmployeeDashboard` page in `frontend/app/routes/hr-advisor/employees.tsx`, focusing on user interface consistency and error handling. The most notable changes are the update to link styling for better visibility and a refinement to the error summary logic.
**UI consistency improvements:**
* Changed the `InlineLink` component to always display an underline, ensuring links are visually distinct and accessible.
**Error handling refinement:**
* Simplified the `ActionDataErrorSummary` logic to always pass `fetcher.data`, improving error display reliability.
**Code clarity:**
* Updated a comment to clarify the handling of the create profile action.
> fix(employees): remove unnecesarry conditional and update View link underline

- frontend/app/components/status-tag.tsx
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/hr-advisor/employees.tsx
[AB#7158](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/7158/)
Improve profile status tags component,
yellow colour meaning you had a task to do, blue meaning you didn't, and the grey meaning it was archived.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative approaches you …
> refactor(frontend): profile status tags

- frontend/app/routes/hiring-manager/request/matches.tsx
- frontend/app/routes/hr-advisor/request/matches.tsx
Fixed the layout in both `request/matches.tsx` to account for smaller screens
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details> …
> fix(frontend): fix layout in matches page's banner

- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/ProfilesController.java
On the Employees table, the "Archive" option is available to all the profiles, so updated the backend to allow archiving profiles having status incomplete/pending/approved
tested by sending archive request from frontend for incomplete and pending profiles.
> refactor(backend): allow archiving profiles

- frontend/app/components/input-multiselect.tsx
[AB#7171](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/7171)
The input multiselect wasn't displaying error messages in the error summary, or being included in the formData in the page action.
> fix(frontend) input-multiselect form errors

- frontend/app/domain/constants.ts
- frontend/app/routes/hiring-manager/request/index.tsx
- frontend/app/routes/hr-advisor/request/index.tsx
- frontend/app/routes/page-components/requests/process-information/form.tsx
- frontend/app/routes/page-components/requests/validation.server.ts
[AB#6878](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6878/)
update selection process type constant for request for clarity
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide …
> refactor(frontend): selection process type constant for request

- frontend/app/routes/hiring-manager/request/index.tsx
fix the progress bar completion ratio on hiring manager request route
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers understand the …
> refactor(frontend): fix the progress bar completion ratio on hiring manager request route

- gitops/prod/cronjobs.yaml
- gitops/prod/external-secrets.yaml
- gitops/prod/kustomization.yaml
Add a cron job to the prod cluster that periodically syncs security groups.
> feat(gitops): add cron job for group syncronization

- frontend/app/.server/resources/currentWFAStatus.json
- frontend/app/domain/constants.ts
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/page-components/employees/employment-information/form.tsx
- frontend/app/routes/page-components/employees/validation.server.ts
> chore(frontend) cherry-pick #883 into release/v1.0.1

- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/RequestService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/RequestStatusUpdateModel.java
```
If the event  is complete 
Requestor is in "hr-advisor" security group
Current Status is PENDING_PSC or PENDING_PSC_NO_VMS
If it is,
then the status is set to PSC_GRANTED
send a notification with ???, sent to the ??? do we need to send PSC clearance number?
If not, should return a 404
```
Notification logic ignored for now. 
<details>
```shell
```
</details>
<details> …
> Requests API - Add complete event

- frontend/app/components/contextual-alert.tsx
- frontend/app/routes/hiring-manager/request/index.tsx
- frontend/tests/components/__snapshots__/contextual-alert.test.tsx.snap
- frontend/tests/components/contextual-alert.test.tsx
Modified the `ContextualAlert` component and added unit tests.  There were quite a few things we didn't need, like `ref`, interpolated styles vs `cn`, etc.
> refactor(frontend) contextual-alert

- frontend/app/components/alert-message.tsx
- frontend/app/components/profile-card.tsx
- frontend/app/components/status-tag.tsx
- frontend/app/routes/hiring-manager/request/profile.tsx
- frontend/app/routes/hr-advisor/request/profile.tsx
Doing some cleanup and noticed inconsistencies in the app when it comes to conditional styling.
> refactor(frontend) use cn in favour of string interpolation

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/MatchEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/MatchFeedbackEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/MatchStatusEntity.java
- MATCH
- CD_MATCH_STATUS
- CD_MATCH_FEEDBACK
Add the above tables as entities in the project.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative approaches you …
> Add match related entities

- frontend/app/.server/domain/services/mock-data.ts
- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hr-advisor/request/index.tsx
Display correct action buttons for hr-advisor request corresponding to the request status following the flow [on figma](https://www.figma.com/design/R75ntV67ucgc6UXWbEwhdN/VacMan-Main?node-id=3062-101837&t=iZaj1K88LOqcTNJQ-0)
Added the Archive dialog box, when the Archive button is clicked, that opens the dialog box that can be dismissed. The action on Archive will be done in another pr.
Added Re-assign dialog box, when the Reassign button is clicked, that open the dialog box that can be dismissed. The Action on re-assign will be done in another pr.
**For Re-assign**: Re-assign only shows up for HR advisors who haven't picked up the request.
Before a request is picked up by anyone, all HRAs see [this page](https://www.figma.com/design/R75ntV67ucgc6UXWbEwhdN/VacMan-Main?node-id=2174-66778&t …
> refactor(frontend): display action buttons for hr-advisor request corresponding to the request status

- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
Profile Card component was [updated](https://github.com/DTS-STN/vacman/pull/953), so updating the employee and hr-advisor/employee-profile route to show edit links on employee profile cards
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any …
> refactor(frontend): show edit links on employee profile cards

- frontend/app/routes/hiring-manager/request/index.tsx
Fixed language requirement and security requirement displaying a code instead of the actual label
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative approaches …
> fix(frontend): fixed displaying language requirement and security requirement

- frontend/app/.server/domain/services/request-service-mock.ts
- frontend/app/routes/hr-advisor/request/index.tsx
[AB#6878](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6878)
hr advisor pick up the request
updated the mocks so that the hr advisor is assigned when the request is picked up
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers understand the visual impact of your changes, if relevant.
> feat(frontend): hr advisor pick up the request

- frontend/app/routes/hr-advisor/request/index.tsx
[AB#6878](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6878)
hide reassign to me button for inactive requests
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
> refactor(frontend): hide reassign to me button for inactive requests
