DTS-STN/vacman

- frontend/app/.server/domain/services/branch-service-default.ts
- frontend/app/.server/domain/services/branch-service-mock.ts
- frontend/app/.server/domain/services/branch-service.ts
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/tests/.server/domain/services/branch-service-default.test.ts
- frontend/tests/.server/domain/services/branch-service-mock.test.ts
[AB#6133](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6133)
[AB#6152](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6152)
- added [oxide](https://www.npmjs.com/package/oxide.ts) package to return `Option ` with `find` and `Result` with `get`
- update mock service and default service for ESDC branch
- added tests for mock and default services
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
pnpm run …
```
> refactor(frontend): update mock and default services for esdc branch

- frontend/app/.server/locales/app-en.json
- frontend/app/.server/locales/app-fr.json
- frontend/app/components/button-link.tsx
- frontend/app/components/button.tsx
- frontend/app/routes/profile/personal-information.tsx
[AB#6229](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6229)
add cancel button on personal information screen as shown in figma.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> feat(frontend): add cancel button on personal information screen

- frontend/app/.server/domain/services/branch-service-default.ts
- frontend/app/.server/domain/services/language-for-correspondence-service-default.ts
- frontend/app/.server/domain/services/language-for-correspondence-service-mock.ts
- frontend/app/.server/domain/services/language-for-correspondence-service.ts
- frontend/app/routes/profile/personal-information.tsx
- frontend/app/routes/profile/validation.server.ts
[AB#6133](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6133)
[AB#6206](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6206)
- update mock service and default service for preferred language of correspondence service to use [oxide](https://www.npmjs.com/package/oxide.ts) package to return Option with find and Result with get
- update Personal information page to consume data coming from preferred language of correspondence service
<details>
```shell
```
</details>
<details>
```shell
pnpm …
```
> refactor(frontend): update preferred language of correspondence service

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/profile/employment-information.tsx
- frontend/app/routes/profile/validation.server.ts
[AB#6251](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6251)
[AB#6260](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6260)
Added following fields and respective validations for substantive position on Employment information screen
- substantive position (group and level)
- branch
- directorate
- province
- city
On selecting Province, the respective cities are in the drop down
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> feat(frontend): add fields for substantive position on Employment information screen

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/.server/locales/gcweb-en.ts
- frontend/app/.server/locales/gcweb-fr.ts
- frontend/app/components/collapsible.tsx
- frontend/app/i18n-routes.ts
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/employee/profile/validation.server.ts
[AB#6262](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6262)
[AB#6266](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6266)
add reference preferences screen
add  fields for language profile, referral availability, alternation opportunities and employment tenure
add the corresponding locals and validation strings
update the route on employee profile to redirect to reference preferences screen
Next steps:
Add the fields for:
Classification groups and level (multi-select drop down)
Work locations(multi-select drop down)
<details>
```shell
pnpm run …
```
> feat(frontend): add reference preferences screen

- .github/workflows/build-and-test.yaml
This PR updates the GitHub Actions workflow to include a new job that builds and tests the `backend` project. 
The job runs only when changes are detected in the `backend` directory.
Marking as draft until #148 is merged as it fixes broken `backend` tests.
This has been previously tested on the `nick/in-memory-tests` branch.
See https://github.com/DTS-STN/vacman/actions/runs/15901374508
> ci: Adding backend build and test job

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/components/app-bar.tsx
- frontend/app/components/card.tsx
- frontend/app/routes/employee/index.tsx
- frontend/app/routes/index.tsx
- frontend/tests/components/__snapshots__/app-bar.test.tsx.snap
- frontend/tests/components/__snapshots__/card.test.tsx.snap
- Removed unused locales from app-en and app-fr files.
- Fixed html errors indicated by [w3c validator](https://validator.w3.org/#validate_by_input)
- - Duplicate ID "menu-label" on the app menu bar (updated the id on app menu)
- Updated the Card component to accommodate the "button" element so that following html errors indicated by [w3c validator](https://validator.w3.org/#validate_by_input) are fixed. The fix was to change div to span element, as span are allowed inside button element.
- - Element "div" not allowed as child of element "button" in this context on the main dashboard
- - Element "div" not allowed as child of element "button" in this context on the employee dashboard
- Updated the heading level to h2 from h3 for cards. There was h1 for the page header, then h3 for card …
> feat(frontend): fix html errors and remove unused locale values

- gitops/nonprod/base/vacman-backend/deployments.yaml
- gitops/nonprod/base/vacman-backend/kustomization.yaml
- gitops/nonprod/overlays/dev/configs/vacman-backend.yaml
- gitops/nonprod/overlays/dev/kustomization.yaml
- Added `base` deployment for `backend` with container, probes, and resource limits
- Added `dev` overlay with environment-specific Kustomize configuration
- `ConfigMap` generator added for `application-local.yaml` overrides
These changes have been tested locally (via port-forwarding) and applied to the cluster.
Connection to MSSQL Server will be handled in a future PR.
> feat(gitops): Add base and overlay files for `backend` support

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/language-for-correspondence-service-default.ts
- frontend/app/.server/domain/services/language-for-correspondence-service-mock.ts
- frontend/app/.server/domain/services/language-for-correspondence-service.ts
- frontend/app/.server/resources/preferredLanguageForCorrespondence.json
- frontend/app/routes/employee/profile/index.tsx
[AB#6277](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6277)
update the language of correspondence service
- Add the `code` field to the mock data
- Add new functions for:
- - get by code
- - find by code
- - find localized by id
- - get localized by code
- - find localized by code
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): update the language of correspondence service

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/UserRepository.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/UserService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/UsersController.java
- backend/src/test/java/ca/gov/dtsstn/vacman/api/data/repository/UserRepositoryTest.java
- backend/src/test/java/ca/gov/dtsstn/vacman/api/service/UserServiceTest.java
- backend/src/test/java/ca/gov/dtsstn/vacman/api/web/UsersControllerTest.java
This pull request adds functionality to retrieve a user by their network name across the repository, service, and controller layers. The most important changes include introducing a new method in `UserRepository`, updating `UserService` to support the new retrieval method, and adding a new endpoint in `UsersController`.
* [`backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/UserRepository.java`](diffhunk://#diff-f015137b1db2975563b19bc413db635a84ebe191dc8f91cb8554dfe9fab525a4R18-R19): Added `findByNetworkName(String networkName)` method to allow querying users by their network name.
* [`backend/src/main/java/ca/gov/dtsstn/vacman/api/service/UserService.java`](diffhunk://#diff-976db1c7259d084d38bd7ca417d672fc44552661afdd0061aa0b9db238d7792eR100-R103): Introduced …
> feat(users): add endpoint to retrieve user by network name

- frontend/app/.server/domain/services/branch-service-default.ts
- frontend/app/.server/domain/services/branch-service-mock.ts
- frontend/app/.server/domain/services/branch-service.ts
- frontend/app/.server/domain/services/directorate-service-default.ts
- frontend/app/.server/domain/services/directorate-service-mock.ts
- frontend/app/.server/domain/services/directorate-service.ts
- frontend/app/.server/domain/services/makeApiRequest.ts
- frontend/app/routes/employee/[id]/profile/employment-information.tsx
- frontend/app/routes/employee/[id]/profile/index.tsx
- frontend/app/routes/employee/[id]/profile/validation.server.ts
- frontend/tests/.server/domain/services/branch-service-default.test.ts
- frontend/tests/.server/domain/services/branch-service-mock.test.ts
[AB#6281](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6281)
[AB#6282](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6282)
update branch and directorate service to connect with work unit api endpoint
There is single endpoint work-unit for getting the branches and directorates. The branches have no parent, while directorates have a parent work-unit. On the frontend we need both lists separately, so separating them at service level, getting the directories if work unit have a parent, and getting the branches if the work unit have no parent.
While displaying the data, we need only the work unit, the directorate name and branch name can be extracted from work unit.
For validating the pr:
run the api locally.
call the default service directly
and set the env variable to point to …
> refactor(frontend): update branch and directorate service

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/classification-service-default.ts
- frontend/app/.server/domain/services/classification-service-mock.ts
- frontend/app/.server/domain/services/classification-service.ts
- frontend/app/routes/employee/[id]/profile/employment-information.tsx
- frontend/app/routes/employee/[id]/profile/index.tsx
- frontend/app/routes/employee/[id]/profile/referral-preferences.tsx
- frontend/app/routes/employee/[id]/profile/validation.server.ts
[AB#6280](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6280)
update service for classification.
The classification JSON file have only two fields `id` and `name`, so used the `name` field for reading `code`, `nameEn`, and `nameFr` fields as these three fields have same data currently.
For validating the pr:
run the API locally.
call the default service directly
and set the env variable to point to the local API
<details>
```shell
```
</details>
<details> …
> refactor(frontend): update service for classification

- frontend/app/routes/employee/[id]/profile/index.tsx
Fix banner overflow on edit-profile page.
> fix(frontend): adjust background width on edit-profile page

- frontend/app/components/error-boundaries.tsx
- frontend/app/root.tsx
- frontend/tests/components/__snapshots__/error-boundaries.test.tsx.snap
This PR moves the client environment variables from the document `<body>` to the document `<head>` to prevent a <mark>Cannot destructure property '...' of 'globalThis.__appEnvironment'</mark> issue in chromium based browsers.
> fix(frontend): move client-env script to document head

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/CityEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/ClassificationRepository.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/LanguageReferralTypeRepository.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/LanguageRepository.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/WorkUnitRepository.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/ClassificationService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/EducationLevelService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/LanguageReferralTypeService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/LanguageService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/WfaStatusService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/UserReadModel.java
Fix most compiler warnings. The vast majority of them were because of unused imports.
> chore(backend): fix compiler warnings

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/components/card.tsx
- frontend/app/routes/index.tsx
- frontend/tests/components/__snapshots__/card.test.tsx.snap
Small PR to get familiar with the project.  Updates index route (`/`) to align with figma.
Quick note: buttons shouldn't be styled as links (this will get flagged in an a11y audit).  In other apps, we've added a hover state with an underline.
> refactor(frontend) update index

- frontend/app/routes/employee/[id]/profile/employment-information.tsx
- frontend/app/routes/employee/[id]/profile/personal-information.tsx
- frontend/app/routes/employee/[id]/profile/referral-preferences.tsx
- frontend/app/routes/employee/[id]/profile/validation.server.ts
- frontend/app/utils/phone-utils.ts
[AB#6245](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6245)
[AB#6252](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6252)
[AB#6263](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6263)
Load profile data for the following routes: 
- Personal information
- Employment information
- Referral preferences
The phone number wasn't loaded on the input phone number, so added a function to convert the string to E164 in phone utils
Changed the input field for work email from `disabled` to `readOnly`, A read-only input field cannot be modified by the user, but its value is still included when the form is submitted.
Before submitting this PR, ensure that you have completed the following. You can fill these out now, or after creating …
> feat(frontend): load profile data for routes

- frontend/app/routes/employee/[id]/profile/index.tsx
[AB#6477](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6477)
Fix wfa effective date and wfa end date not showing on the employee profile. The constant for wfa status was changed to `code` instead of `id`. Applying the same logic to check the code and then display the dates based on wfa status.
Add this data to the profile mock to view the Employment information, the wfa effective date and wfa end date are not displayed:
employmentInformation: {
classificationId: '904190000',
workUnitId: '294550010',
cityId: '411290002',
wfaStatusId: '4',
wfaEffectiveDate: undefined,
wfaEndDate: undefined,
hrAdvisor: 5,
},
> bugfix(frontend): fix wfa effective date and wfa end date not showing on the employee profile

- frontend/app/.server/domain/services/api-client.ts
- frontend/app/.server/domain/services/branch-service-default.ts
- frontend/app/.server/domain/services/city-service-default.ts
- frontend/app/.server/domain/services/classification-service-default.ts
- frontend/app/.server/domain/services/directorate-service-default.ts
- frontend/app/.server/domain/services/employment-tenure-service-default.ts
- frontend/app/.server/domain/services/language-for-correspondence-service-default.ts
- frontend/app/.server/domain/services/language-referral-type-service-default.ts
- frontend/app/.server/domain/services/province-service-default.ts
- frontend/app/.server/domain/services/province-service-mock.ts
- frontend/app/.server/domain/services/province-service.ts
- frontend/app/.server/domain/services/wfa-status-service-default.ts
- frontend/tests/.server/domain/services/branch-service-default.test.ts
[AB#6419](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6419)
update the default services to pass along the error in Err instead of defining http status code
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): update the default services to pass along the error in Err

- frontend/app/.server/domain/services/profile-service-mock.ts
The prevailing convention in the service mock implementations appears to be using arrow functions for the method signatures.  This PR makes that change and also updates the 'save' methods to use the same update logic/convention.
> chore(frontend) stick to conventions in profile service mock

- frontend/.env.example
- frontend/app/.server/domain/services/branch-service-default.ts
- frontend/app/.server/domain/services/city-service-default.ts
- frontend/app/.server/domain/services/classification-service-default.ts
- frontend/app/.server/domain/services/directorate-service-default.ts
- frontend/app/.server/domain/services/employment-tenure-service-default.ts
- frontend/app/.server/domain/services/language-for-correspondence-service-default.ts
- frontend/app/.server/domain/services/language-referral-type-service-default.ts
- frontend/app/.server/domain/services/province-service-default.ts
- frontend/app/.server/domain/services/wfa-status-service-default.ts
update the api path for code tables only. All the code tables are behind path /codes, while rest of the endpoints are not.
> refactor(frontend): update the api path for code tables

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/routes/employee/[id]/profile/index.tsx
Updated the source of employee name and work email on profile view. Currently the Employee profile is displaying the name and work email of the logged-in user. The Employee Profile can be viewed by Employee, HR Advisor and Hiring manager. So, updating the name and work email address to reflect the name and work email of the employee profile being viewed.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, …
> refactor(frontend): update the employee name and work email source

- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/profile-service.ts
- frontend/app/routes/employee/[id]/profile/personal-information.tsx
- frontend/tests/.server/routes/index.test.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
- frontend/tests/.server/utils/profile-access-utils.test.ts
- frontend/tests/.server/utils/profile-utils.test.ts
Added default/mock calls for saving personal information in profile-service-default and profile-service-mock
[ADO#6249](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6249)
[ADO#6301](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6301)
> Added default/mock calls for saving personal information

- frontend/app/routes/employee/[id]/profile/referral-preferences.tsx
Adds sort order to the classifications selected by the user which makes visually easier to process and group information.  Sorts only on the choice tags so as to eliminate unexpected side effects in the fetched data.
> fix(frontend) make sort classifications in referral-preferences

- frontend/app/.server/locales/gcweb-en.ts
- frontend/app/.server/locales/gcweb-fr.ts
- frontend/app/components/choice-tags.tsx
- frontend/app/routes/employee/[id]/profile/referral-preferences.tsx
Adds 'clear group' functionality to the `ChoiceTags` for when the user only wants to clear grouped choices.
> refactor(frontend) add clear group functionality to choice tags

- frontend/app/routes/employee/profile/referral-preferences.tsx
This pull request fixes a submission problem with the referall preferences page. It includes a change in the `action` function within the `frontend/app/routes/employee/profile/referral-preferences.tsx` file. The change simplifies how form data is processed by removing the mapping of certain fields to `Number` and instead directly using the values as they are retrieved.
* [`frontend/app/routes/employee/profile/referral-preferences.tsx`](diffhunk://#diff-7d92dd055cee605ad765f0b40f5c5490be9cfedc0b8ce20c4254002a2305eceeL64-R74): Removed `.map((val) => Number(val))` transformations for `languageReferralTypeIds`, `classificationIds`, `workLocationCitiesIds`, and `employmentTenureIds` fields, allowing the form data to be used directly without converting to numbers.
> fix(frontend): remove Number() conversion from referral preferences page

- backend/src/main/java/ca/gov/dtsstn/vacman/api/security/SecurityUtils.java
- backend/src/test/java/ca/gov/dtsstn/vacman/api/security/SecurityUtilsTest.java
This pull request introduces `SecurityUtils`, a new utility class designed to centralize and simplify common Spring Security operations.
This class provides static methods to reliably access the `SecurityContext`, retrieve the current user's authentication details (including their Entra ID/OID), and check user authorities without duplicating code across the application.
> feat(backend): Add SecurityUtils

- frontend/app/@types/express-session.ts
- frontend/app/routes/employee/index.tsx
- frontend/app/routes/index.tsx
[AB#6515](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6515)
Call `getCurrentUser` which is an api call to the backend to `/user/me`, this will either return the current user, or 404.  If a 404 is returned (an error will propagate in our frontend), we make a subsequent call to `registerCurrentUser` which is a call to `/users/me` with a `POST` request.  The returned user is then store in the session.
> feature(frontend) add currentUser to session

- frontend/app/.server/domain/services/user-service-default.ts
[AB#6575](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6575)
The backend expects `/users?{role}=true`
Technically we're only handling `hr-advisors` for this iteration, so the route could just hardcode that, but in the spirit of making the least amount of changes, this does the job.
> chore(frontend) update getUsersByRole default impl

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/user-service-mock.ts
- frontend/app/routes/employee/index.tsx
- frontend/app/routes/employee/profile/privacy-consent.tsx
- frontend/tests/.server/domain/services/user-service-integration.test.ts
- frontend/tests/.server/domain/services/user-service-mock.test.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
[AB#6557](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6557)
Update `registerCurrentUser` based on what the backend expects in payload (i.e. `languageId`).
> refactor(frontend) update registerCurrentUser

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/profile-service.ts
- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
[AB#6571](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6571)
update to #344.  The `updateProfile` method should send the entire profile instead of partial data
> fix(frontend) make updateProfile accept the entire profile not partial data

- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/profile-service.ts
- frontend/tests/.server/domain/services/profile-service-default.test.ts
- frontend/tests/.server/routes/index.test.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
- frontend/tests/.server/utils/profile-access-utils.test.ts
- frontend/tests/.server/utils/profile-utils.test.ts
This pull request adds support for retrieving the current user's profile to the `ProfileService` interface and its implementations. It introduces a new `getCurrentUserProfile` method, which is implemented for both the default and mock profile services. The change also updates related types and test mocks to ensure consistency and testability.
**Profile service enhancements:**
* Added the `getCurrentUserProfile(session: AuthenticatedSession): Promise<Option<Profile>>` method to the `ProfileService` type definition in `profile-service.ts`, allowing retrieval of the currently authenticated user's profile.
* Implemented `getCurrentUserProfile` in `profile-service-default.ts` to fetch the current user's profile from the backend API, including error handling for network issues, not found …
> feat(frontend): add getActiveProfile profile service method

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/user-service-default.ts
- frontend/app/.server/domain/services/user-service-mock.ts
- frontend/app/.server/domain/services/user-service.ts
- frontend/app/.server/utils/hiring-manager-registration-utils.ts
- frontend/app/.server/utils/hr-advisor-registration-utils.ts
- frontend/app/.server/utils/profile-access-utils.ts
- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/tests/.server/domain/services/user-service-mock.test.ts
- frontend/tests/.server/routes/hiring-manager.test.ts
- frontend/tests/.server/routes/index.test.ts
- frontend/tests/.server/utils/hiring-manager-registration-utils.test.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
- frontend/tests/.server/utils/profile-access-utils.test.ts
[AB#6584](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6584)
removes `getUserByActiveDirectoryId`
please review carefully since I've had to call other user service/profile service methods to make these changes work.
> chore(frontend) remove getUserByActiveDirectoryId

- frontend/app/.server/domain/services/api-client.ts
- frontend/tests/.server/domain/services/non-advertised-appointment-service-default.test.ts
as discussed in chat update api client to add access token
Note: run the api locally, and set the ENABLE_LOOKUP_FIELD_SERVICES_MOCK=false in .env file, the code tables still load, so current functionality is still intact
> refactor(frontend): update api client

- frontend/app/routes/employee/profile/index.tsx
[AB#6562](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6562/)
load employee profile from profile/me endpoint
This pr address the flow on the Profile page Loader, to Call GET profile/me to get the profile data and throwing 404 if not found, and then getting the user from GET /users/me to display the user name, work email and work phone from user data.
Since the route for hr-advisor have it's own employee profile route, so it wouldn't effect anything
<details>
```shell
```
</details>
<details> …
> refactor(frontend): load employee profile from profile/me endpoint

- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/profile-service.ts
- frontend/app/routes/employee/profile/privacy-consent.tsx
- frontend/tests/.server/domain/services/profile-service-default.test.ts
- frontend/tests/.server/domain/services/profile-service-mock.test.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
[AB#6595](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6595/)
register profile service use api client
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): register profile service use api client

- frontend/app/.server/domain/services/user-service-default.ts
- frontend/app/.server/domain/services/user-service-mock.ts
- frontend/app/.server/domain/services/user-service.ts
- frontend/app/routes/employee/index.tsx
- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/tests/.server/domain/services/user-service-integration.test.ts
- frontend/tests/.server/domain/services/user-service-mock.test.ts
This pull request refactors the `UserService` interface and its implementations to simplify user retrieval and registration logic, enhance consistency, and remove unnecessary dependencies on authentication token claims. The changes affect both the default and mock user services, as well as related tests and usage across the codebase.
* Updated the `UserService` interface so that `getUsersByRole`, `getUserById`, and `registerCurrentUser` now require an `accessToken` parameter and no longer accept or depend on `IDTokenClaims`. This change is reflected in both the default and mock implementations. [[1]](diffhunk://#diff-0e99b214d616b21343a09e70650b4c92bb0ce12f9b3f675a1624b06c4b74e1a6L1-R10) [[2]](diffhunk://#diff-62c486944910a42d24279df0e88bb23944b577fcad66e84732377e216fd6787dR13-R65) …
> refactor(frontend): Use apiClient as base for User Service methods

- frontend/app/routes/employee/index.tsx
- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/privacy-consent.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hiring-manager/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employees.tsx
There is a deprecation warning in the `meta` functions.  The suggested remedy is to use `loaderData` instead of `data`
> chore(frontend) update meta function to fix deprecation warning

- frontend/app/i18n-routes.ts
Since `/employee/profile` will be accessed directly via `getCurrentUserProfile()` which calls `/profile/me?active=true` under the hood, we don't need to include the `id` of the user in the path param since it a) isn't used, and b) can be retrieved from the returned profile.
> chore(frontend) remove id param from path in employee routes

- frontend/app/routes/employee/index.tsx
- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
The `userId` can be obtained from the current profile instead of `context.session.authState.idTokenClaims.oid`, which as Greg says, the frontend should never need to do.
> chore(frontend) remove unnecessary userId extraction in employee/profile routes

- frontend/app/components/dashboard-card.tsx
- frontend/app/i18n-routes.ts
- frontend/app/routes/employee/index.tsx
- frontend/app/routes/hr-advisor/index.tsx
As discussed in [this closed pr#292 ](https://github.com/DTS-STN/vacman/pull/292) prefer anchor tags over forms with buttons for navigation (or whatever we use for navigation since buttons are an anti-pattern and more used for onscreen events, like triggering popups, showing animations, submitting forms for input validation, etc)
The Dashboard card component is used on employee index and hr advisor index page, replacing duplicate code for ActionCard.
<details>
```shell
``` …
> refactor(frontend): move dashboard card to separate file

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/routes/employee/profile/index.tsx
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
There were some issues with the profile status not switching to be in a "pending approval" state once it had been successfully submitted.
> fix(frontend) profile status once profile submitted

- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/.server/domain/services/profile-service.ts
- frontend/tests/.server/domain/services/profile-service-default.test.ts
This pull request makes a small change to the profile service by removing the `includeUserData` parameter from the profiles listing logic.
> fix(profile): remove includeUserData from getAllProfiles parameters and query key

- frontend/app/routes/hr-advisor/employees.tsx
- frontend/tests/.server/domain/services/profile-service-default.test.ts
Since `includeUserData` was removed from the `profileParams` in the `listAllProfiles` call, it can be removed in the frontend loader and test calls.
> chore(frontend) remove unused includeUserData

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/ClassificationProfileEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/ProfileCityEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/ProfileEmploymentOpportunityEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/entity/ProfileLanguageReferralTypeEntity.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/ProfileService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/ProfilesController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/ProfilePutModel.java
A refactoring of the `PUT /profiles/{id}` operation:
* Creating a dedicated "Put" model for the profile that accepts IDs instead of models
* Including some missed fields from the initial implementation, including the associative entities
* Associative entities required a somewhat non-trivial solution due to unique key constraints rubbing up against Hibernate's execution model ([see Javadoc for `syncAssociations` for more information](https://github.com/DTS-STN/vacman/commit/b56b326cf669acf13eea5fb5face4d3dcbe8bf57#diff-f1d8e719f2f5513f698923e4b548011b36edcd20345247480bdbcc758cec64adR255-R273))
* Associative entities required to override `equals` and `hashCode` methods to properly trigger "dirty" changes
_(check all that apply by placing an `x` …
> refactor(backend): Overhaul PUT /profiles/{id}

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/match-status-service-default.ts
- frontend/app/.server/domain/services/match-status-service-mock.ts
- frontend/app/.server/domain/services/match-status-service.ts
- frontend/app/errors/error-codes.ts
[Unrelated to the current integration work being done, which is why the target is `main`]
[AB#6700](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6700)
Adds the match status service which will be used in Iteration 2 for request/match.
> feat(frontend) add match-status-service

- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
[AB#6769](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6769/)
[AB#6779](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6779/)
save personal information in profile data
Running the api locally, the profile data and user data are saved  from personal information screen
> refactor(frontend): save personal information in profile data

- frontend/app/routes/page-components/employees/employment-information/form.tsx
Fixed wfaStatus error not appearing for field
Changed it to use "`formErrors?.wfaStatusId`"
[ADO#6777](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6777)
> Fixed wfaStatus error not appearing for field

- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/tests/.server/domain/services/profile-service-mock.test.ts
IMO, simulating network latency with promises in the mocks and simulating failed tokens isn't useful, so I'm removing it.
> refactor(frontend) remove simulations checks from profile service mocks

- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
[AB#6784](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6784)
Makes the payload consistent with the other profile routes.
Also encountered a new 'bug' [AB#6790](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6790) which I've picked up.
> refactor(frontend) referral-preferences updateProfileById payload

- gitops/nonprod/overlays/int/configs/vacman-frontend.conf
This pull request updates the `vacman-frontend.conf` configuration for the `int` (integration) environment to disable several mock services that were previously enabled. This change ensures the application uses real backend services instead of mocked data.
Configuration changes:
* Set `ENABLE_LOOKUP_FIELD_SERVICES_MOCK`, `ENABLE_USER_SERVICES_MOCK`, and `ENABLE_PROFILE_SERVICES_MOCK` to `false` to disable mock services for lookups, user, and profile data in the integration environment.
> config(frontend): disable mock services for int environment

- frontend/app/components/input-help.tsx
- frontend/tests/components/__snapshots__/date-picker-field.test.tsx.snap
- frontend/tests/components/__snapshots__/input-checkboxes.test.tsx.snap
- frontend/tests/components/__snapshots__/input-field.test.tsx.snap
- frontend/tests/components/__snapshots__/input-file.test.tsx.snap
- frontend/tests/components/__snapshots__/input-help.test.tsx.snap
- frontend/tests/components/__snapshots__/input-pattern-field.test.tsx.snap
- frontend/tests/components/__snapshots__/input-phone-field.test.tsx.snap
- frontend/tests/components/__snapshots__/input-radios.test.tsx.snap
- frontend/tests/components/__snapshots__/input-select.test.tsx.snap
- frontend/tests/components/__snapshots__/input-textarea.test.tsx.snap
According to the W3C HTML validator, `<detail>` cannot be a child of `<span>`.
> fix(frontend) details not allowed as child of span

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hr-advisor/employees.tsx
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F63
Classic a11y failure that is always flagged.  Text like "read more", "view", are not accessible names for links.
> fix(frontend) F63: Failure of Success Criterion 2.4.4 due to providing link context only in content that is not related to the link

- frontend/app/components/back-link.tsx
- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
Long story short, while looking for a11y issues, I noticed the "back to profile" links were using `"<"` in the link text, which would be read by a screenreader as "Less than back to profle".  Seeing as how we have this back to profile link on several pages, I guess it can be extracted out as a component.
> refactor(frontend) BackLink component

- frontend/app/.server/utils/auth-utils.ts
- frontend/tests/.server/utils/auth-utils.test.ts
This pull request enhances authentication logic by ensuring that JWT expiration is properly checked and handled in authentication utilities. It also adds comprehensive tests for these behaviors to improve reliability and maintainability.
**Authentication logic improvements:**
* Added a check in `requireAuthentication` (in `auth-utils.ts`) to detect if the JWT access token is expired, and redirect the user to the login page if necessary.
* Updated `requireAllRoles` and `requireAnyRole` to always call `requireAuthentication` first, ensuring both authentication and token validity are enforced before checking user roles. [[1]](diffhunk://#diff-bef08db62a238509ba3a1332c3810ebe53954b1305b064d623d445b9b618f784L58-R75) [[2]](diffhunk://#diff-bef08db62a238509ba3a1332c3810ebe53954b1305b064d623d445b9 …
> fix(auth): check for token expiry and re-auth

- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
[AB#6805](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6805/)
Fixed this bug: 
Save all the data in profile, then edit the personal information or employment information section, the referral preferences section becomes empty.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> bugfix(frontend): fix error on saving profile

- frontend/app/routes/employee/profile/privacy-consent.tsx
So the bug in Team, "Privacy notice statement - pop links out into a different page", actually means external links should open in a new tab, which I agree with.
> refactor(frontend) add new tab indicator and external link to /privacy-consent

- frontend/app/domain/constants.ts
- frontend/app/routes/page-components/employees/referral-preferences/form.tsx
In the employment-information form, if "not selected" is checked, all other checked boxes should be unselected.  If a user then selects another box while "not interested" is checked, the "not interested" box should then become unchecked.
> refactor(frontend) unselect employment oppourtunities if not interested is selected

- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
[AB#6807](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6807)
In short, calling `getUserById` has permission implications if the user doesn't own the resource, or isn't an hr-advisor which is problematic for employees in the profile summary screen when they try to view the name of their hr advisor.  Instead we can recycle the `getHrAdvisors` utility function and filter on the hr advisor id.
> refactor(frontend) use getHrAdvisors instead of getUserById

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hiring-manager/requests.tsx
[AB#6712](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6712)
Adds the content for when a hiring manager first hits /hiring-manager/requests and they have no active or archived requests.  Future PR(s) will address posting to the api to create new requests, and for displaying tables of requests.
> feat(frontend) /hiring-manager/requests

- frontend/app/routes/page-components/employees/referral-preferences/form.tsx
There's no reason why these need to be controlled inputs, so we can remove the unnecessary `useState`s
> refactor(frontend) remove unnecessary usestate expressions

- frontend/app/.server/domain/models.ts
Since it seems we've stuck to the convention of mirroring the backend api models for our frontend services...here's some of the models we'll need for the frontend request-service (yet to be implemented).
> feat(frontend) add request models

- frontend/app/components/date-picker-field.tsx
- frontend/app/components/input-legend.tsx
- frontend/app/components/input-radios.tsx
- frontend/app/components/input-select.tsx
- frontend/app/routes/page-components/employees/employment-information/form.tsx
- frontend/app/routes/page-components/employees/referral-preferences/form.tsx
- frontend/tests/components/__snapshots__/input-select.test.tsx.snap
[AB#6820](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6820/)
Screen reader wasn't reading some information provided in the screen shot, refer the task above.
Added the aria-describedby to the fieldset of input-select, input-radio and date-picker components, as recommended by the ITAO accessor. The screen reader NVDA now reads the information.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): screen reader would read the legend

- frontend/app/components/input-multiselect.tsx
Addresses a11y ticket [6826](https://dev.azure.com/DTS-STN/VacMan/_boards/board/t/VacMan%20Team/Stories?System.IterationPath=VacMan%5CCurrent%20Work%2CVacMan%5CMVP%20-%20GET%20IT%20DONE%2CVacMan%5CMVP%20Iteration%202&workitem=6826)
This pull request makes a small update to the `InputMultiSelect` component to improve accessibility and user interaction. The main change is ensuring the checkbox within each option is not directly focusable or clickable, which helps prevent nested input selection and keeps the focus behavior consistent.
- Accessibility and interaction improvements:
* In `frontend/app/components/input-multiselect.tsx`, removed the `aria-required` prop from `InputCheckbox`, set `tabIndex={-1}` and added `pointer-events-none` to make the checkbox non-focusable and non-interactive …
> fix(frontend): prevent keyboard interaction on nested controls in InputMultiSelect

- frontend/app/routes/employee/profile/index.tsx
Addresses [bug 6844](https://dev.azure.com/DTS-STN/VacMan/_boards/board/t/VacMan%20Team/Stories?System.IterationPath=VacMan%5CCurrent%20Work%2CVacMan%5CMVP%20-%20GET%20IT%20DONE%2CVacMan%5CMVP%20Iteration%202&workitem=6844)
When submitting an incomplete profile, the user should be presented with "Please complete all required fields before submitting your profile"
This pull request updates the `EditProfile` component in `frontend/app/routes/employee/profile/index.tsx` to consistently use `fetcher.data` (now referenced as `formActionData`) instead of `actionData` for displaying form submission results and error states. This change ensures that the component correctly reflects the latest form state when using `fetcher.Form`.
**Form state management improvements:**
* Introduced …
> fix(frontend): profile submission would not present error with incomplete profile

- frontend/app/components/profile-card.tsx
This pull request makes a small change to the `ProfileCard` component to improve accessibility and semantic HTML. The only change is replacing a paragraph tag with a heading tag for error messages.
- Changed the error message element from a `<p>` to an `<h3>` tag in `profile-card.tsx` to use more appropriate semantic HTML for headings.
> a11y(frontend): styled <p> elements must not be used as headings

- frontend/app/components/input-field.tsx
- frontend/tests/components/__snapshots__/app-bar.test.tsx.snap
- frontend/tests/components/__snapshots__/input-field.test.tsx.snap
- frontend/tests/components/__snapshots__/loading-button.test.tsx.snap
- frontend/tests/components/__snapshots__/menu.test.tsx.snap
- frontend/tests/components/__snapshots__/search-bar.test.tsx.snap
Addresses [6833](https://dev.azure.com/DTS-STN/VacMan/_boards/board/t/VacMan%20Team/Stories?System.IterationPath=VacMan%5CCurrent%20Work%2CVacMan%5CMVP%20-%20GET%20IT%20DONE%2CVacMan%5CMVP%20Iteration%202&workitem=6833)
This pull request updates the `InputField` component to ensure the label's `htmlFor` attribute correctly matches the input's `id`, improving accessibility and test reliability. The associated tests and snapshots have been updated to reflect this change.
Accessibility improvements:
* Updated the `InputField` component so that the `InputLabel`'s `htmlFor` prop uses `ids.input` instead of the generic `id`, ensuring it matches the actual input element's id.
Test updates:
* Updated all relevant test snapshots in `input-field.test.tsx.snap` to expect the correct `for` attribute …
> a11y(frontend): fix issue with label "for=" attributes being inaccurate

- frontend/app/components/input-select.tsx
- frontend/tests/components/input-select.test.tsx
Addresses [6839](https://dev.azure.com/DTS-STN/VacMan/_boards/board/t/VacMan%20Team/Stories?System.IterationPath=VacMan%5CCurrent%20Work%2CVacMan%5CMVP%20-%20GET%20IT%20DONE%2CVacMan%5CMVP%20Iteration%202&workitem=6839)
This pull request improves the accessibility and behavior of the `InputSelect` component when the `label` prop is empty. The main changes ensure that the label element and related ARIA attributes are only rendered when a label is provided, and adds a test to verify this behavior.
Accessibility and conditional rendering improvements:
* Updated the `InputSelect` component to only render the label element and set the `aria-labelledby` attribute if the `label` prop is provided, preventing unnecessary or empty ARIA attributes when the label is empty. …
> a11y(frontend): conditionally render label and aria-labelledby based on label presence

- frontend/app/.server/locales/gcweb-en.ts
- frontend/app/.server/locales/gcweb-fr.ts
- frontend/app/components/choice-tags.tsx
- frontend/app/components/input-multiselect.tsx
- frontend/app/components/input-radios.tsx
- frontend/app/routes/page-components/employees/referral-preferences/form.tsx
- frontend/tests/components/__snapshots__/input-multiselect.test.tsx.snap
- frontend/tests/components/input-multiselect.test.tsx
[AB#6824](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6824)
Fixed the issue as described in the task Required field not marked as required, by updating the input-multiselect component to use field set and legend (instead of the label), and setting the aria-required for the combo box div.
Passed the ariaDescribedById param to the input-multiselect as done in input-select, date-picker-field and input-radios to fix another a11y issue mentioned [in task](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6820/). 
Updated the choice tag, so that the province name is also conveyed along with the city in choice tag remove button announcement by screen reader.
Before submitting this PR, ensure that you have completed the following. You can …
> a11y(frontend): required field not marked as required

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/components/input-textarea.tsx
- frontend/app/routes/hiring-manager/request/somc-conditions.tsx
- frontend/tests/components/__snapshots__/input-textarea.test.tsx.snap
[AB#6727](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6727)
To make this more palatable, I'm breaking this PR into smaller incremental chunks.  This PR adds the page content for the SOMC screen.  I've added todos for future work.  I've also changed the text-area component.  The absolute positions of the character limit was causing elements to overlap.
> feat(frontend) add somc-conditions page content

- backend/pom.xml
- backend/src/main/java/ca/gov/dtsstn/vacman/api/config/SpringDocConfig.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/json/JsonMergePatchHttpMessageConverter.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/json/JsonPatchException.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/json/JsonPatchHttpMessageConverter.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/json/JsonPatchMediaTypes.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/json/JsonPatchOperation.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/json/JsonPatchProcessor.java
- backend/src/test/java/ca/gov/dtsstn/vacman/api/json/JsonMergePatchHttpMessageConverterTests.java
- backend/src/test/java/ca/gov/dtsstn/vacman/api/json/JsonPatchHttpMessageConverterImplTests.java
- backend/src/test/java/ca/gov/dtsstn/vacman/api/json/JsonPatchProcessorTests.java
Add a JsonPatch processor and Spring message converters to allow for `application/json-patch+json` patch endpoints
> feat(backend): implement JsonPatchProcessor to allow for JSON-Patch endpoints

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/ProfileStatusRepository.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/ProfileService.java
There was a hidden `NullPointerException` in the way that profile statuses were being fetched and used in `ProfileService`. This PR switches to find-by-example along with a throw `asResourceNotFoundException()` to instead alert the consumer about the missing resource with a 404 response code.
> refactor(backend): switch to query-by-example in ProfileService

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/EventRepository.java
Trivial PR: add missing `@Repository` annotation to `EventRepository`.
This change does nothing.. it's only to enforce consistency across the codebase.
> fix(backend): add missing @Repository annotation

- frontend/app/routes/hiring-manager/requests.tsx
Convention is to `return i18nRedirect(...)` in the page actions (based on observation)
> fix(frontend) change throw to return for i18nredirect in action

- frontend/app/.server/domain/services/request-service-default.ts
- frontend/app/.server/domain/services/request-service-mock.ts
- frontend/app/.server/domain/services/request-service.ts
This method is no longer needed.
> refactor(frontend) remove getRequestProfileById from request-service

- frontend/app/routes/dev/oidc-provider.tsx
- frontend/app/routes/layout.tsx
Adds roles to the the dev user John Doe so we can effectively navigate to the hr-advisor/hiring-manager routes in `dev` without having to comment out auth checks in the root loader, or add and remove these roles during development.  This has the implication of being redirected to `/hr-advisor/index` instead of `/employees/index` upon hitting the root since the user is now an hr-advisor.
> refactor(frontend) add roles for dev user John Doe

- frontend/app/routes/hiring-manager/index.tsx
Used the background image in layout for hiring manager dashboard keeping it consistent with other index pages (avoid scroll bar on dashboard)
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
> refactor(frontend): use the background image in layout for hiring manager dashboard

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hiring-manager/request/position-information.tsx
- frontend/app/routes/hr-advisor/request/position-information.tsx
- frontend/app/routes/page-components/requests/position-information/form.tsx
- frontend/app/routes/page-components/requests/validation.server.ts
[AB#6887](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6887/)
[AB#6888](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6888)
Copied the position information screen from hiring manager to hr advisor route. Fixed some layout and validations, as the form didn't save when any "Language Requirement" option was selected that doesn't require the language profile.
##Additional information
To test: visit the route /hr-advisor/request/1/position-information
<details>
```shell
```
</details>
<details>
<summary>Unit and e2e …
> feat(frontend): hr advisor -> position information screen

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hiring-manager/requests.tsx
- frontend/app/routes/page-components/requests/tables/requests-tables.tsx
Since the active/inactive requests tables will be used in multiple routes (hr-advisor + hiring-manager), they are are candidate for compentizing.  This PR does exactly that and a future PR will add this component to `/hr-advisor/requests`.
> refactor(frontend) componentize requests tables

- frontend/app/routes/hiring-manager/request/process-information.tsx
- frontend/app/routes/hr-advisor/request/process-information.tsx
- frontend/app/routes/page-components/requests/process-information/form.tsx
Adds content/loader for `request/process-information`.  The action still needs to be implemented for both hr-advisor/hiring-manager.
> refactor(frontend) request/process-information

- frontend/app/components/page-title.tsx
- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
The idiomatic vacman way to add an `h1` heading to the page is via the `PageTitle` component.  The only problem with this approach is that the container `div` has default styles on it which we sometimes might want to override.  No matter...we can just throw on an additional prop for that.
There's also some weird text overflow for the timestamp when the viewport is scaled to a mobile device.  Adding additional responsiveness to the decorative banner for that..
> refator(frontend) add containerClassName prop to PageTitle

- frontend/playwright.config.ts
- frontend/vite.config.ts
[AB#6907](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6907)
Presumably during e2e tests there's a `302` to `login.ms.com` when the tests expect `/`.  This would suggest that the environment is using the `AZURAD` auth provider outside of development.  I believe overriding the webSever env in the playwright config is the way to go here.
> refactor(frontend) add env to playwright.config

- frontend/app/.server/domain/services/mockData.ts
- frontend/app/.server/locales/app-en.ts
- frontend/app/routes/hiring-manager/request/submission-details.tsx
- frontend/app/routes/hr-advisor/request/submission-details.tsx
- frontend/app/routes/page-components/requests/submission-detail/form.tsx
- frontend/app/routes/page-components/requests/validation.server.ts
[AB#6895](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6895/)
[AB#6894](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6894/)
Request submission form submitter information
This pr is part of many prs, more form elements will be added in next prs.
This pr deals with showing submitter information on hiring manager and hr advisor route (as the wording is different for both cases).
Next radio button for selecting yes or no will be added in subsequent prs.
Connect with api running locally, on /hr-advisor dashboard and create a new Request, and then navigate to /submission-details, The selection is unselected for new request:
while running mocks, navigate to /hr-advisor/request/1/submission-details or /hiring-manager/request/1/submission-details, the mock data have values, so …
> feat(frontend): Request submission form submitter information

- frontend/app/.server/express/assets/403.html
- frontend/app/.server/express/assets/500.html
[AB#6914](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6914) -- fix 500 error page
Fix the rendering of the canada watermark in static error pages.
**Fun fact:** this error also occurs on <https://www.canada.ca/errors/500.html> 🎉 
before:
after:
> fix(frontend): fix canada watermark on static error pages

- frontend/app/routes/page-components/requests/validation.server.ts
(Yes, I'm aware of the import side-effects and that they need to get fixed.  This is to prevent copying unnecessary code while transitioning)
We can work with a `readonly` copy of the resource data for validations.  There's no need to map the values to mutable objects.
> refactor(frontend) remove useless mapping in validations

- frontend/app/.server/domain/services/request-service-mock.ts
The service calls to fetch resource data in the mock request service can be simplified, specifically in `updateRequestById`
> refactor(frontend) simplify updateRequestById service calls in mock-service

- frontend/app/routes/hiring-manager/request/position-information.tsx
- frontend/app/routes/hiring-manager/request/process-information.tsx
- frontend/app/routes/hiring-manager/request/submission-details.tsx
- frontend/app/routes/hr-advisor/request/position-information.tsx
- frontend/app/routes/hr-advisor/request/process-information.tsx
- frontend/app/routes/hr-advisor/request/submission-details.tsx
- frontend/app/routes/page-components/requests/validation.server.ts
Similar to #736
This PR removes top level service calls in the request validations in order to prevent import side-effects.
> refactor(frontend) remove top level service calls in request validations

- frontend/app/components/input-multiselect.tsx
- frontend/tests/components/__snapshots__/input-multiselect.test.tsx.snap
I noticed there was 0 margin on the legend of the input-multiselect component.  This PR adds a consistent `mb-2` which aligns with the other input components.
> fix(frontend) add margin bottom to input-multiselect legend

- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/ProfileService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/mapper/ProfileEntityMapper.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/ProfilesController.java
In order to facilitate a future change that will allow HR advisors to create profiles for other users, the `ProfileService.createProfile(..)` method needs to be refactored so it doesn't always associate the profile with the currently logged in user.
> refactor(backend): `ProfileService.createProfile()` now accepts a profile

- frontend/app/routes/hiring-manager/request/index.tsx
[AB#6837](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6837)
Show all fields in the position information card on hiring-manager request page. added logic to handle the language profile fields.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, …
> refactor(frontend) Complete request page position information card

- frontend/app/i18n-routes.ts
- frontend/app/routes/index.tsx
- frontend/e2e/index.spec.ts
- frontend/tests/.server/routes/index.test.ts
[AB#6971](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6971)
- add a splash page, that redirect English to /en/employee and Français to /fr/employe
- removed auto redirect for hr-advisor
- update the hr advisor route for French
- update the tests and e2e tests
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include …
> feat(frontend): add a splash page

- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/personal-information.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hiring-manager/request/position-information.tsx
- frontend/app/routes/hiring-manager/request/somc-conditions.tsx
- frontend/app/routes/hiring-manager/request/submission-details.tsx
- frontend/app/routes/hr-advisor/employee-profile/employment-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/personal-information.tsx
- frontend/app/routes/hr-advisor/employee-profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/request/position-information.tsx
- frontend/app/routes/hr-advisor/request/somc-conditions.tsx
- frontend/app/routes/hr-advisor/request/submission-details.tsx
There's no sense in assigning `actionData.errors` to a variable only to pass it into a component.  Just pass it directly into the component without assignment.
> refactor(frontend) consolidate actionData errors

- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/RequestService.java
FROM [AB#6642](https://dev.azure.com/DTS-STN/4c33b941-c811-479f-b181-dfd5292182ff/_workitems/edit/6642):
```
If the event  is vmsNotRequired
Requestor is in "hr-advisor" security group
Current Status is HR_REVIEW
If it is,
then the status is set to PENDING_PSC_NO_VMS
If not, should return a 404
```
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
pnpm …
```
> Add the vmsNotRequired status change logic

- frontend/app/.server/locales/gcweb-en.ts
- frontend/app/.server/locales/gcweb-fr.ts
- frontend/app/components/data-table.tsx
- frontend/app/components/pagination.tsx
- frontend/app/routes/hr-advisor/employees.tsx
- frontend/app/utils/math-utils.ts
- frontend/app/utils/pagination-utils.ts
Addresses [BUG 6837](https://dev.azure.com/DTS-STN/VacMan/_boards/board/t/VacMan%20Team/Stories?System.IterationPath=VacMan%5CCurrent%20Work%2CVacMan%5CMVP%20-%20GET%20IT%20DONE%2CVacMan%5CMVP%20Iteration%202&workitem=6837)
This pull request introduces a reusable, accessible pagination component and integrates server-side pagination into the HR Advisor Employees dashboard. It also improves locale support for pagination labels and adds utility functions for pagination logic. The changes enhance the user experience for large datasets and provide better accessibility and internationalization.
**Pagination component and utilities**
* Added a new reusable `Pagination` component (`frontend/app/components/pagination.tsx`) with accessible markup, customizable subcomponents, and screen reader …
> feat(frontend): adding server-side pagination to hr-advisor/employees

- frontend/app/routes/hiring-manager/request/process-information.tsx
- frontend/app/routes/hr-advisor/request/process-information.tsx
- frontend/app/routes/page-components/profile/validation.server.ts
- frontend/app/routes/page-components/requests/validation.server.ts
- frontend/app/utils/date-utils.ts
`date-utils` can be refactored to take advantage of `oxide.ts`.  This removes semi-redundant code used a in a few spots.
> refactor(frontend) date-utils

- frontend/app/.server/domain/services/request-service-mock.ts
- frontend/app/routes/hiring-manager/request/index.tsx
- frontend/app/routes/hiring-manager/request/submission-details.tsx
[AB#6894](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/6894/)
updated mocks to save/update the request submission details for the hiring manager. Also updated the request index screen to correctly display the saved data.
Next steps: 
update the hr-advisor request submission detail to update request
update French translations when available
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain …
> feat(frontend): update request submission detail for hiring manager

- frontend/app/routes/page-components/profile/validation.server.ts
- frontend/app/utils/validation-utils.ts
moving `optionalString` to `validation-utils` for better™ organization
> refactor(frontend) cleanup profile/validation.server

- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/AbstractBaseRepository.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/data/repository/ProfileRepository.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/ProfileService.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/dto/ProfileQuery.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/ProfilesController.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/ProfileReadFilterModel.java
- backend/src/main/java/ca/gov/dtsstn/vacman/api/web/model/mapper/ProfileModelMapper.java
This PR allows for finer-grained filtering when fetching profiles. It isn't an exhaustive filtering solution, but it can easily be extended to be.
An example of how to filter:
```shell
GET /api/v1/profiles?hrAdvisorId=840&hrAdvisorId=841&statusId=1&statusId=2
```
Notice how multiple values can be passed.
> feat(backend): allow finer-grained filtering when fetching profiles

- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/profile-service-default.ts
- frontend/app/.server/domain/services/profile-service-mock.ts
- frontend/app/routes/hr-advisor/employees.tsx
- frontend/tests/.server/domain/services/profile-service-default.test.ts
- frontend/tests/.server/domain/services/profile-service-mock.test.ts
This pull request updates the filtering logic for profile queries to support new filter parameters and improves type safety and consistency across the codebase. The main changes include replacing the old `'hr-advisor'` parameter with `hrAdvisorId`, introducing a new `statusIds` filter, and updating related service, route, and test files to use the new parameters and types.
**Profile Query Parameter Improvements**
* Changed the `ProfileQueryParams` type in `models.ts` to use `hrAdvisorId` instead of `'hr-advisor'`, and added a new `statusIds` array for filtering by profile status IDs.
**Service Layer Updates**
* Updated both the default and mock profile services (`profile-service-default.ts` and `profile-service-mock.ts`) to use the new `hrAdvisorId` and `statusIds` parameters for …
> feat(frontend): update ProfileQueryParams to include statusId and hrAdvsiorId

- frontend/app/components/data-table.tsx
- frontend/app/routes/hr-advisor/employees.tsx
This pull request enhances the hr-advisors/employees table filtering functionality by introducing a controlled selection for status codes and ensuring consistent synchronization between the client UI and backend queries. The changes improve both usability and accessibility, allowing users to filter employees by status more intuitively and ensuring that filter selections persist across navigation and updates.
**Filtering and selection improvements:**
* Added controlled selection support to the `DataTableColumnHeaderWithOptions` component via new `selected` and `onSelectionChange` props, enabling parent components to manage the selected status codes and react to changes.
* Updated the employee dashboard to map between status codes and IDs, allowing the UI to display status codes while the …
> feat(frontend): allow controlled selection for hr-advisor/employees table Status column

- frontend/app/.server/application-context.ts
- frontend/app/.server/express/handlers.ts
- frontend/app/@types/react-router.ts
- frontend/app/entry.server.tsx
- frontend/react-router.config.ts
- frontend/tests/.server/routes/index.test.ts
- frontend/tests/.server/utils/privacy-consent-utils.test.ts
This PR *incrementally* adopts the new middleware pattern introduced in React Router v7. This is part of an effort to modernize the application's routing and data-loading mechanisms.
It will be the first PR of many that will eventually update all of the route loaders and actions.
- enabled the `v8_middleware` future flag in `react-router.config.ts`
- introduced a new `applicationContext` to provide application-level data (eg: `nonce`, `session`) to loaders and actions using the new middleware pattern
- updated the serverside request handler to use `RouterContextProvider` and the new `applicationContext`
- included a temporary compatibility shim to allow for a gradual migration from the old `AppLoadContext` to the new middleware pattern, as recommended in the React Router documentation …
> feat(frontend): incrementally adopt RRv7 middleware

- frontend/app/routes/employee/profile/index.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
One a11y issue that we received is low colour contrast between foreground and background, specifically in the profile index banner.  This happens because content overflows its container and white/gray text appears on a white background.  
The banner itself is hard to fix, due in part to it needing to break out of its container to occupy the full screen width, thus we've placed it `absolute`.  This has the unfortunate side-effect of taking it out of the document flow for styling, and anything below the banner will float up and underneath it.  
I think we should let the banner occupy the full height of its content (always), instead of just giving a fixed height to accommodate the decorative banner.  This will allow the banner to never overflow text.  Unfortunately, we have to give fixed …
> fix(frontend) profile index decorative banner

- frontend/app/routes/employee/profile/employment-information.tsx
- frontend/app/routes/employee/profile/referral-preferences.tsx
- frontend/app/routes/hr-advisor/employee-profile/index.tsx
This pull request updates the logic for re-approving employee profiles in two routes by correcting the identifier used when updating profile status. The change ensures that the correct profile ID is passed to the `updateProfileStatus` service.
Profile status update fix:
* In both `employment-information.tsx` and `referral-preferences.tsx`, the call to `profileService.updateProfileStatus` now uses `currentProfile.id` instead of `currentProfile.profileUser.id` to correctly identify the profile being updated. [[1]](diffhunk://#diff-ba69a87dc77db29a07b93b48dabec7c6edf88c9acbf2279422228f5192c84c7dL83-R83) [[2]](diffhunk://#diff-7d92dd055cee605ad765f0b40f5c5490be9cfedc0b8ce20c4254002a2305eceeL93-R93)
> fix(frontend): fix updateProfileStatus calls to use currentProfile.id

- frontend/app/routes/layout.tsx
The decorative banner in the dashboard screen now breaks out of the container to occupy the full width of the screen.  It is responsive and will be hidden when the view port is `<'sm'` (768px)
> fix(frontend) decorative banner in dashboard screens

- .github/copilot-instructions.md
This pull request adds a comprehensive set of Copilot instructions for the `DTS-STN/vacman` multi-app workspace, providing an architectural overview, conventions, local workflow steps, integration notes, and important "gotchas." These instructions are designed to help Copilot understand the structure and best practices for working with the repository.
Repository documentation improvements:
* Added a detailed architecture and flow section describing interactions between the browser, frontend, backend, and database, including key technologies and directory locations.
* Documented conventions for both frontend and backend development, specifying usage patterns, error handling, feature flags, routing, and security practices.
* Outlined local development workflows for each app (frontend, …
> feat(docs): add Copilot instructions for multi-app workspace setup

- gitops/nonprod/overlays/uat/patches/deployments-backend.yaml
- gitops/nonprod/overlays/uat/patches/deployments-frontend.yaml
This pull request updates the container image versions for both the backend and frontend deployments in the UAT environment to newer release candidate versions.
Deployment image updates:
* Updated the backend container image in `gitops/nonprod/overlays/uat/patches/deployments-backend.yaml` to `1.0.1-RC112` for the `vacman-backend` service.
* Updated the frontend container image in `gitops/nonprod/overlays/uat/patches/deployments-frontend.yaml` to `1.0.1-RC099` for the `vacman-frontend` service.
> fix(deployments): update backend and frontend images to version 1.0.1-RC112 and 1.0.1-RC099 respectively

- gitops/nonprod/overlays/uat/patches/deployments-backend.yaml
- gitops/nonprod/overlays/uat/patches/deployments-frontend.yaml
This pull request updates the container image versions for both the backend and frontend deployments in the UAT environment. These changes ensure that the UAT environment uses the latest release candidates for both services.
**Deployment image updates:**
* Updated the backend deployment (`vacman-backend`) image to version `1.0.1-RC114` in `deployments-backend.yaml` to use the latest backend build.
* Updated the frontend deployment (`vacman-frontend`) image to version `1.0.1-RC101` in `deployments-frontend.yaml` to use the latest frontend build.
> fix(deployments): update backend and frontend images to version 1.0.1-RC114 and 1.0.1-RC101 respectively

- frontend/app/.server/locales/gcweb-en.ts
- frontend/app/.server/locales/gcweb-fr.ts
- frontend/app/components/data-table.tsx
This pull request enhances the accessibility and user experience of the data table filters by adding localized ARIA labels and a visible indicator of selected filter options. The changes ensure that screen readers announce the number of selected filters, and users can visually see the count next to the filter title.
**Accessibility and Localization Improvements:**
* Added new localized ARIA label strings for filter headers in both English (`gcweb-en.ts`) and French (`gcweb-fr.ts`) locale files, supporting singular and plural forms. [[1]](diffhunk://#diff-3ff5c497124df65a907bf39e75c074666731ce4420420b5554b66cd8e86833bdR89-R92) [[2]](diffhunk://#diff-6abebf11f63fb7b28cb0190ede327b75e2edb81ed23000243c0f23ec9c8cb38bR91-R94)
* Integrated the translation hook (`useTranslation`) in the …
> feat(frontend): display selection count in DataTableColumnHeaderWithOptions

- gitops/prod/deployments.yaml
This pull request updates the container images for both the backend and frontend services in the production deployment configuration to newer versions.
Deployment image updates:
* Updated the `vacman-backend` container image to version `1.0.1-5454f682` in `gitops/prod/deployments.yaml`
* Updated the `vacman-frontend` container image to version `1.0.1` in `gitops/prod/deployments.yaml`
> fix(deployments-prod): update backend and frontend images to version 1.0.1

- frontend/app/routes/hiring-manager/request/index.tsx
The status tag is only displayed when the status of the request is draft, same as the other cards
> fix(frontend) showStatus submission-details card

- frontend/app/routes/page-components/requests/somc-conditions/form.tsx
The requests pages haven't been a11y audited yet, but they'' tell us to put lang attributes on these inputs since both english and french is displayed on the screen.
> fix(frontend) add lang attribute to somc textareas

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hiring-manager/requests.tsx
- frontend/app/routes/page-components/requests/tables/requests-tables.tsx
[AB#7181](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/7181/)
hiring manager can copy existing request to create a new one.
On copying a request, the user is redirected to the newly created request displaying copied data.
Current user is saved as the Submitter, while the information for hiring manager, hr advisor and sub delegated manager are not copied.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant …
> feat(frontend): copy request

- frontend/containerfile
Sit down, grab a coffee, and prepare yourselves for what is undoubtedly the most pivotal infrastructure upgrade of the fiscal year. After minutes of painstaking research, nonexistent whiteboard sessions, and at least one existential crisis in the cluster room, I am proposing that we upgrade our Node.js runtime from the now-archaic and frankly dangerous v20.19.0 to the glorious, enlightened, and paradigm-shifting **v20.20.0**.
I know what you're thinking: "*But it's just a point release!*" To which I say, that's what they said about the wheel, the printing press, and sliced bread. This is not merely an update; this is an **ascension**.
This is not a change to be taken lightly. The following rigorous testing protocol has been executed:
1. **Full test suite execution:** ran `npm test`.. …
> chore(frontend): strategic runtime upgrade to Node.js v20.20.0

- backend/src/main/java/ca/gov/dtsstn/vacman/api/service/RequestService.java
- frontend/app/.server/domain/models.ts
- frontend/app/.server/domain/services/request-service-default.ts
- frontend/app/.server/domain/services/request-service-mock.ts
- frontend/app/.server/domain/services/request-service.ts
- frontend/app/domain/constants.ts
- frontend/app/routes/hiring-manager/request/index.tsx
This pull request refactors the request status update functionality across both the frontend and backend, improving type safety and extensibility. The main change is replacing the previous string-based status update with a new `RequestStatusUpdate` object, which uses an explicit event type. This update affects service interfaces, implementations, and related constants, and also expands the set of supported request event types.
**API and Service Layer Refactoring:**
* The `RequestService` interface and its implementations (`request-service-default.ts`, `request-service-mock.ts`) now use a `RequestStatusUpdate` object instead of a raw string for status changes. The return type is updated to provide the updated `RequestReadModel` instead of just `void`. …
> feat(frontend/backend): hiring manager request submission API integration

- backend/src/main/java/ca/gov/dtsstn/vacman/api/security/OwnershipPermissionEvaluator.java
- frontend/app/.server/domain/services/request-service-default.ts
- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/hiring-manager/request/index.tsx
**Backend**
- `OwnershipPermissionEvaluator.java`
- Improved code formatting and readability in comments and method signatures.
**Frontend**
- Request Service
- Fixed the deleteRequestById method to correctly pass the accessToken as the fourth argument to the API client.
**Localization**
- Added generic error messages for both English and French.
- Expanded delete request error messages, including a specific message for when deletion is not allowed (submitted requests).
**Hiring Manager View Request Page**
- Added type guard and error result type for action errors.
- Updated the delete action to prevent deletion of non-draft requests, returning a localized error message if attempted.
- Improved alert message logic:
- Introduced a helper function (getAlertConfig) to determine alert type …
> feat(frontend): hiring-managers can delete draft requests

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/page-components/requests/validation.server.ts
[AB#7202](https://dev.azure.com/DTS-STN/VacMan/_workitems/edit/7202)
Added validation for the projected end date in `process-information.tsx` to check if the date is after today.
<details>
```shell
```
</details>
<details>
```shell
pnpm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary …
> fix(frontend): validation for future date check on projected end date

- frontend/app/.server/locales/app-en.ts
- frontend/app/.server/locales/app-fr.ts
- frontend/app/routes/page-components/requests/process-information/form.tsx
This pull request introduces a small but important update to the process information form and its related translations. The main change is to clarify that approval from the relevant committee is required, and to enforce this requirement in the form.
**Form validation and translation improvements:**
* Marked the "approval received" field as required in both the English and French translation files to clarify that this information is mandatory. [[1]](diffhunk://#diff-c66a209c5fef0d4d98edf70489cfdb2984a3ad3dd1644b6a7e7206f45c48a304L219-R219) [[2]](diffhunk://#diff-bfa4fd2b422d9379133c2ec7d691186e037bcc1bbbd45f60d83910a525d578eaL222-R222)
* Added the `required` attribute to the `priorityEntitlementRationale` field in the `ProcessInformationForm` component to ensure users cannot submit the …
> fix(frontend): process-information labels should be clearer
